python3 gps_bus1.py &
python3 gps_bus2.py &
python3 gps_bus3.py &
python3 gps_bus4.py &
python3 gps_barr1.py &
python3 gps_barr2.py &
python3 biometric_bus1.py &
python3 biometric_bus2.py &
python3 biometric_bus3.py &
python3 biometric_bus4.py &
python3 gps_iiit.py &
python3 temperature1.py &
python3 temperature2.py &
python3 light1.py &
python3 light2.py &
python3 temperature3.py &
python3 temperature4.py &
python3 light3.py &
python3 light4.py &
